version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - PIGNUS_VERSION=$(python3 src/pignus/version.py)
      - echo "Building Pignus Version ${PIGNUS_VERSION}"
      - mkdir docker/pignus
      - cp -r src/ docker/pignus
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd docker/
      - docker build --no-cache -t pignus/pignus:${PIGNUS_VERSION}  .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
